backend:
  name: git-gateway
  branch: master

media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
